name: CI
on:
  push:
    branches:
      - hexo-blog
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo-blog
      - name: Setup node 
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "zguishen@foxmail.com"
          git config --global user.name "zguishen"
          npm install hexo-cli -g
          npm install tiddlywiki -g
          npm install
      - name: Hexo deploy
        run: |
          hexo clean
          tiddlywiki tiddlywiki --build index
          mkdir -p public/wiki
          mv tiddlywiki/output/index.html public/wiki
          hexo d
